# Generated by Django 5.0.2 on 2024-02-23 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_Creacion_de_tablas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingrediente',
            old_name='decripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='preparacion',
            old_name='plato',
            new_name='platoId',
        ),
        migrations.AlterUniqueTogether(
            name='preparacion',
            unique_together={('orden', 'platoId')},
        ),
    ]
