"""removi not null tabla pedido

Revision ID: 189548427402
Revises: 4d2cc6604c49
Create Date: 2024-02-08 17:14:07.868406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '189548427402'
down_revision = '4d2cc6604c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('barman_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('barman_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
